name: CI Voll Med

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configura Docker Compose
      run: |
        if [ -f /usr/local/bin/docker-compose ]; then
        sudo rm /usr/local/bin/docker-compose
        fi
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version


    - name: Roda Docker Compose
      run: docker-compose up -d

    - name: Executa testes unit치rios
      run: mvn -B verify
    
    - name: Gera relat칩rio Jacoco
      run: mvn jacoco:prepare-agent verify

    - name: An치lise est치tica
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=vandersoncr_vollmed-api
